### PR TITLE
Added Dockerfile and default values to user table.

### PR DESCRIPTION
**Pull request by DracoMilesX**

### CODE REVIEW

**Comment by ruchern** [comment]
Revert the users.table to upstream/master and your conflicts should be resolved.

**Comment by maierfelix** [comment]
@DracoMilesX Please create a new pr as this one is a mess in my eyes right now. Also dont mix the docker related changes with the db related ones.

**Comment by Kidel** [comment]
you probably also want to add protobuf clone, make and make install, plus env variable setup.

**Comment by maierfelix** [comment]
@Kidel I will add precompiled protobuf files as soon as a stable release is ready

**Comment by Kidel** [comment]
I was talking about the dockerfile, but sure, that would make it easier for most people.

**Comment by DracoMilesX** [comment]
@Kidel google protobuf is included? Line 35/36

**Comment by Kidel** [comment]
you're right, sorry I didn't notice.

**Pull request closed without merging**
