### PR TITLE
Solve error on some node versions!

### PR DESCRIPTION
**Pull request by GabrielTK**
Worked for me! This solves the following (frequent) error:
`TypeError: _this2.print is not a function` on Windows.

### CODE REVIEW

**Comment by GabrielTK** [comment]
`Update response.js` fixes the ToS Screen

**Comment by DracoMilesX** [comment]
Only thing I am wondering is I remember @Cronick once making a PR for the print2 function and @maierfelix afterwards changing it back. Maby on accident?

**Comment by Badley187** [comment]
https://github.com/maierfelix/POGOserver/pull/163

youre right @DracoMilesX

**Comment by GabrielTK** [comment]
That's really strange. Maybe it was by accident??? I don't know.

**Pull request merged**
