### PR TITLE
Added this.skipTutorial();

### PR DESCRIPTION
**Pull request by Sillyblower**
Now it has no unknown request in the console.

### CODE REVIEW

**Comment by maierfelix** [comment]
Skip tutorial isnt used anymore - see parseJSON method which parses the players tutorial state from users table

**Comment by Sillyblower** [comment]
Strange, because i cant get pass the TOS screen ... 
Unkown request: MARK_TUTORIAL_COMPLETE 
I did a full clean install even the DB but when i put skiptutorial in the source than there is no problem?
Any idea?

**Comment by maierfelix** [comment]
The tutorial state is stored in the database now, edit users.tutorial to your needs like:
````
{"0":1,"1":1,"3":1,"4":1,"7":1}
````

**Comment by Sillyblower** [comment]
I know it´s stored in the BD , but it don´t change at all. 
Whatever i write 1or 0 .... see screenshot. 
mark_tutorial_complete

**Comment by marcomarotta** [comment]
same for me. edited all 1 in db users with tutorial name...still cant get past tos screen.

**Comment by ruchern** [comment]
@maierfelix Are you using MongoDB or what?

**Comment by Sillyblower** [comment]
Even with the new update there is no passing the TOS screen .... i´m still using the this.skiptutorial()
The {"0":1,"1":1,"3":1,"4":1,"7":1} don´t work at all. How to fix this error?

**Comment by DracoMilesX** [comment]
The issue remains most likely because it doesn't write the user to the database so the default values don't do anything. Manual inserting the user into the database should bypass it for now.

**Pull request closed without merging**
