### PR TITLE
Removed logs from repository. Added the folder into gitignore.

### PR DESCRIPTION
**Pull request by ruchern**

### CODE REVIEW

**Comment by maierfelix** [comment]
Please add a slash after logs

**Comment by MZorzy** [comment]
need to manual do
mkdir logs
or will have not logs on linux

**Comment by ruchern** [comment]
@maierfelix Done.

**Comment by berner90** [comment]
What to do if i get MySql error ER_Bad_Db_Error Unknown Db pogosql

**Pull request merged**
