### PR TITLE
Api - Server crashes after spawning in pokemon

### PR DESCRIPTION
**Pull request by Sythe97**
Type in spawn (username) ARTICUNO 1, and the server crashes. And none of the other commands work /clients doesnt work.

### CODE REVIEW

**Comment by Schwalli89** [comment]
I can't install the Server:

see
http://fs5.directupload.net/images/160905/t9hrhs34.jpg

**Comment by jop02** [comment]
@Schwalli89 i have got the same problem

396 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-protobuf"
397 error node v6.5.0
398 error npm  v3.10.3
399 error code ELIFECYCLE
400    
400 error Exit status 1
401 error Failed at the node-protobuf@1.3.3 install script 'node-gyp rebuild'.
401 error Make sure you have the latest version of node.js and npm installed.
401 error If you do, this is most likely a problem with the node-protobuf package,
401 error not with npm itself.
401 error Tell the author that this fails on your system:
401 error     node-gyp rebuild
401 error You can get information on how to open an issue for this project with:
401 error     npm bugs node-protobuf
401 error Or if that isn't available, you can get their info via:
401 error     npm owner ls node-protobuf
401 error There is likely additional logging output above.
402 verbose exit [ 1, true ]

(this was on my windows)

and i want to install this on my linux aswel but where or how do i get the run-linux.sh file becouse i don't see it in the normal download

**Comment by DracoMilesX** [comment]
People pull requests aren't for issues.

The development of this project is still highly experimental do not expect that you can use it properly.

Commands aren't fully implemented yet.

**Comment by jop02** [comment]
@DracoMilesX sorry for submitthing to the wrong section thank you for the fix

**Comment by Schwalli89** [comment]
Sorry. But i dont know where to post it correctly

**Comment by Schwalli89** [comment]
Are u guys having the same problem that u cannot have a look into open and closed issues because of 404? And i cant create a new issue...

**Pull request closed without merging**
