### PR TITLE
Update main.js

### PR DESCRIPTION
**Pull request by Sillyblower**
changed gym_0 to gym_neutral

### CODE REVIEW

**Comment by DracoMilesX** [comment]
Better to make neutral all capital or change the name of the image. Linux might trip over it.

**Comment by Cronick** [comment]
Also make a commit on renaming the file from gym_NEUTRAL.png to gym_neutral.png

**Comment by Sillyblower** [comment]
Sorry, this is my first time using Github.

**Comment by CineXMike** [comment]
Someone knows this error?
http://i64.tinypic.com/52c3uh.png

**Pull request merged**
