### PR TITLE
Updated Dockerfile and supervisord.conf

### PR DESCRIPTION
**Pull request by DracoMilesX**
Added support for apache and the api branch for POGOserver

note: I dunno if you keep the api branch seperated or integrate it to the master branch on a later point? If that happens I will just change the Dockerfile.

### CODE REVIEW

**Comment by Becold** [comment]
# Now
I'll post a "new" DockerFile to super-optimize it when i'll got something that work. Right now, this shit take 3 Go on the HDD which is A LOT.
image
And actually, if the contenair crash, the datas from the DB aren't saved since there is not any mount volume.

# My plan
## Setup 1 process = 1 container. Don't mix process in only 1 container.
Docker suggest to keep 1 container = 1 process. So : 
* 1 contenair for apache (EXPOSE 80 443)
* 1 contenair for mysql (EXPOSE 3306)
* 1 contenair for pogoserver (EXPOSE 3000)
Then, use [docker run --network (...)](https://docs.docker.com/engine/reference/run/#network-settings) to "link them together".
[docker-compose](https://docs.docker.com/compose/overview/) should help us to setup 3 contenairs in 1 command.

## Use alpine light image
Using [alpine images](http://www.sandtable.com/reduce-docker-image-sizes-using-alpine/) should decrease the size of the image. (E.g.: 232MB --> 16MB)

## Setup .dockerignore
And using .dockerignore should slightly decrease it too.

Btw @maierfelix, will you keep the Api branch seperated from Master branch or will you merge it later?

**Comment by DracoMilesX** [comment]
@Becold Thanks for the feedback I added all services into 1 container since it would be the easiest way for people with no to little knowledge about it. And for myself as well so I don't need to switch every time between containers if their are changes.

**Comment by DracoMilesX** [comment]
Well found 3 alpine containers (Not maded by me ofcourse). https://github.com/DracoMilesX/POGOserver/tree/master/Docker Currently testing the node one and then modifying it to include the pogoserver and protobuf.

After this only .dockerignore docker-run and docker-compose need to be figured out/added.

Apache needs to get the api client added unless maierfelix decides to merge it to master.

**Comment by Becold** [comment]
@DracoMilesX I'm currently trying to setup something too. I'll make a PR when it will be stable. :)

**Comment by maierfelix** [comment]
@Becold Possibly merging it later

**Comment by DracoMilesX** [comment]
@Becold did you manage to get it working?

**Comment by maierfelix** [comment]
Can someone approve if the docker files are working?

**Comment by DracoMilesX** [comment]
The new way is atm not working so I will close it.

**Comment by Becold** [comment]
https://github.com/Becold/POGOserver/commit/5fb5d93c3090eb1d90d4ca410258239af0340451
This is what i come up to. (And its **not** working :cry:)

## The stuff that (maybe) work :+1: 
Inside **docker-compose.yml**, i'm using directly the image from the [docker hub repo](https://hub.docker.com/) for apache and mysql.
During my test, Apache was working, I had the api displaying inside http://localhost/ but the api couldnt connect to the server (because he wasnt up). Mysql, I dont know but I once create the database inside it so I guess its working too.

## The stuff that dont work :-1: 
For pogoserver, docker-comppose.yml use automatically this [DockerFile](https://github.com/Becold/POGOserver/blob/5fb5d93c3090eb1d90d4ca410258239af0340451/Dockerfile).

## For your tests and build
Please, edit **docker-compose.yml**. I'm using _Docker for Windows_ and the path for the **volumes** are for Windows setup : 
> For apache and pogoserver, edit all volumes `E:\Lab\Docker\pogoserver` (this is where my git repo is).
> For mysql, just create a random folder somewhere on your hdd and point Docker-compose volume to it.  

Edit **cfg.js** too!

## Usefull command
These commands are usefull to work with all contenairs: 
`docker-compose build` -> (re-)build all the images from docker-compose.yml
`docker-compose up` -> start all the containers 
`docker-compose up --build` -> do both
One problem: the DockerFile take A LOT (like... 30 minutes? I dont know) but A LOT of time to build it at the first time. This is because of the protobuf stuff. The package `apk add protobuf` wasnt working during my test.

These command for only pogoserver image/container : 
Create the image locally : `docker build -t pogoserver .`
Run the image inside a container :  `docker run --rm -P pogoserver -v .:/POGOserver/ -p 3000:3000`

## And... im stuck.
Here is the errors i'm up to : 
image
image

There is somehow a missing package or missing files and I dont know how to properly inject them.

## PS 
1. DockerFile of Pogoserver doesnt clean his package (and the size of the image is very big). Have a look at the dockerfile.
2. For the `apk add` stuff, it take the package from [alpine repo](https://pkgs.alpinelinux.org/packages).
3. I cant continue to work on it atm (I got big projects to work on). Hope you'll find a solution!

**Comment by DracoMilesX** [comment]
1. The first error is solved I think by using the protobuf-dev package. They are the same version but when doing that mine succeeds.
2. The second error should be solved with 1.
3. Well 367MB-1GB still is better then 3GB you could try to replace mysql image with imega/mysql
4. Change under pogoserver in the compose file from `build: .` to `build: /volume4/Drive4/pogoserver/` # It will use DockerFile

I will test it later when my laptop is working with docker have too little free HDD space on my desktop

Considering I am getting a client and server aren't the same version when composing on my NAS.

**Comment by DracoMilesX** [comment]
Well all goes well except when I want to run the pogoserver one.

Both MySQL and Apache connect fine to my local volumes.
Pogoserver does this too for newly created files like the debug log. But for existance files it does not so it crashes with no package.json found or no node_modules found. By the looks of it the COPY command or even a git clone of the repo don't work and delete the files once the creation is completed.

**Comment by Becold** [comment]
On my side:
- Mysql & Apache connect fine to my local volume.
- Mysql wont start. ( http://puu.sh/qZqFe/49782b413d.png )
- Pogoserver found package.json and do correctly `npm install` but cant find babel-es2015 press ( http://puu.sh/qZqGS/38931812a9.png )

**Comment by DracoMilesX** [comment]
Maby you should look in the directory mysql gets placed on ur local disk. I have it sometimes with apache as well that it doesn't remove the .pid file so it gives the warning it's already running.

Dunno about the second one. Installing it for me still works fine but running is the issue since it doesn't store node_modules or the repo on my disk.

**Comment by DracoMilesX** [comment]
@Becold Got it working except the latest commit isn't working because of the pokedex module.
https://github.com/DracoMilesX/POGOserver/commit/13c3dfbb7494a8b06c520877d1b09964f780d50d #

**Pull request closed without merging**
