### PR TITLE
[bug fix] Case Sensitive for Linux

### PR DESCRIPTION
**Pull request by MZorzy**
please note all 5 patch from youyi1314 (don't know how to add all here)
 change "SRC" to "src" fix run-linux.sh and server can start

### CODE REVIEW

**Comment by DracoMilesX** [comment]
Easiest way is for him to merge those branches into master and then submit a PR

**Comment by maierfelix** [comment]
Same issue in ``FortDetails`` and ``GetMapObjects``. Please add them to here :)

**Comment by MZorzy** [comment]
how to add as pull request?  are on 5 different branch ...
https://github.com/maierfelix/POGOserver/commit/089251c3ce40f895edfe0d8e8d6737db3d1f3049
https://github.com/maierfelix/POGOserver/commit/3299218c666bde2c93ac8060430191ef6982a2c9
https://github.com/maierfelix/POGOserver/commit/1560ae196c3cb35180b2229b16cdbf0d5b87dca6
https://github.com/maierfelix/POGOserver/commit/c1aed1e79bff7e629b9a5f1fb587320d4f73f4cf
https://github.com/maierfelix/POGOserver/commit/d2d87701a9d3d95b6d3f83db6648d3f5f3a9b802

**Comment by maierfelix** [comment]
Fixed it in https://github.com/maierfelix/POGOserver/commit/b671dd48b3c9dbeb6f11781ca004ebb4cb640221
Thanks for your contribution

**Pull request closed without merging**
